### PR TITLE
fix completion

### LINKED ISSUE #67: Completion bugs
1. The description of some multiline completion items is broken, probably due to wrong dedentation

image

2. When entering a single dot, the completion sometimes is not triggered

### PR DESCRIPTION
**Pull request by nk-coding**
## bugfixes
- entering a `.` reliably triggers completion again
- formatting of multiline completion items is fixed

## issues
- closes #67

### CODE REVIEW

File: packages/core/src/parser/cstToAstTransformer.ts [hunk 1]
```diff
@@ -398,7 +398,7 @@ export function generateCstToAstTransfromer(parser: Parser): ICstVisitor<never,
                 }
             }
             if (ctx.FaultTolerantToken) {
-                return this.generateFieldAccessExpressionForOnlyDot(baseExpression, ctx.FaultTolerantToken);
+                return this.generateFieldAccessExpressionForOnlyDot(baseExpression, ctx.FaultTolerantToken[0]);
```
Comment (delvh) [inline packages/core/src/parser/cstToAstTransformer.ts:401]: >  When entering a single dot, the completion sometimes is not triggered

How does this fix anything?

**Review by delvh — APPROVED** [review]

File: packages/core/src/parser/cstToAstTransformer.ts (hunk 1 above)
Comment (nk-coding) [reply packages/core/src/parser/cstToAstTransformer.ts:401]: Pretty standard type error
It propagates to the completion range computatation, which thus fails.
This causes the completion then to not trigger.
